openapi: 3.0.0
info:
  title: Users
  description: 'This an API for managing users that exist in the Union Fashion users, allowing any desktop, web, mobile, or device application to integrate with users made via our platform.'
  version: '1.0'
servers:
- url: '{{baseUrl}}'
paths:
  /users:
    post:
      summary: Add User
      description: Creates a new user.
      operationId: addUser
      tags:
        - Users
      requestBody:
        description: 'A user schema.'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              category: Jeans
              brand: Union
              color: black
              gender: m
              unitPrice: 49.99
              unitSalePrice: 29.99
      security:
      - api_key: []
      responses:
        201:
          description: 'Successful creation of user.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                status: success
      deprecated: false
    get:
      summary: Get Users
      description: Pulls a list of all user
      operationId: getUsers
      tags:
        - Users
      parameters:
      - name: query
        in: query
        description: 'A query to search for users by.'
        required: true
        schema:
          type: string
          example: 'shirts'
      security:
      - api_key: []
      responses:
        200:
          description: 'List of users.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
              example:
                status: success
      deprecated: false
  '/users/{userId}':
    get:
      summary: Get User
      description: Retrieves a single user.
      operationId: getUser
      tags:
      - Users
      parameters:
        - name: userId
          in: path
          description: The user ID to retrieve.
          required: true
          schema:
            type: string
            example: user-one
      responses:
        200:
          description: 'Single user.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                status: success
      deprecated: false
      security:
      - api_key: []
    put:
      summary: Update
      description: Supports either full or partial updates.
      operationId: updateUser
      tags:
      - Users
      parameters:
        - name: userId
          in: path
          description: The user ID to retrieve.
          required: true
          schema:
            type: string
            example: user-one
      security:
      - api_key: []
      requestBody:
        description: 'A user object.'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              unitSalePrice: 29.99
        required: true
      responses:
        204:
          description: 'Successfully updated.'
      deprecated: false
    delete:
      tags:
      - Users
      summary: Delete
      description: 'Delete an individual user.'
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          description: The user ID to retrieve.
          required: true
          schema:
            type: string
            example: user-one
      security:
      - api_key: []
      responses:
        204:
          description: 'User deleted.'
      deprecated: false
components:
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
  schemas:
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
    User:
      title: User
      required:
      - identifier
      - name
      type: object
      properties:
        identifier:
          type: string
        name:
          type: string
        description:
          type: string
        image:
          type: string
        url:
          type: string
        brand:
          type: string
        category:
          type: string
        color:
          type: string
        logo:
          type: string
        manufacturer:
          type: string
        material:
          type: string
        model:
          type: string
        releaseDate:
          type: string
        sku:
          type: string
        width:
          type: string
        weight:
          type: string
        depth:
          type: string
        height:
          type: string
      example:
        id: XYZ-JEAN-123
        category: Jeans
        brand: Union
        color: black
        gender: m
        unitPrice: 49.99
        unitSalePrice: 29.99
tags:
- name: Users
  description: 'A user object.'
